spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    username: # set username
    password: # set password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/database/schema.sql
      data-locations: classpath:/database/create.sql
      continue-on-error: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, beans, env, loggers, heapdump, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    heapdump:
      access: unrestricted